### ISSUE TITLE
Need to add a blank resource_pack.yml file

### ISSUE THREAD

**Issue by slingshot322** [crscheid/pocketmine-mp#5]
I was getting a yml parse error when starting the server and just had to add a `--- false` to the reference yml file to get the server to start

**Comment by crscheid** [comment]
Ok thanks. Will look at this when our vacation ends. ;-)

**Comment by crscheid** [comment]
@slingshot322 Can you add a little more context? Do you have plugins already in your instance that are not loaded when using the server? Is there something specific about your configuration above and beyond a stock install?

I started with a stock server from a fresh install and there is no complaints about requiring a `resource_pack.yml` file or a YML parse error in general.

Note that the default installation contains the following in `resource_packs/resource_pack.yml` file:

```yml
#This configuration file controls global resources used on your PocketMine-MP server.

#Choose whether players must use your chosen resource packs to join the server.
#NOTE: This will do nothing if there are no resource packs in the stack below.
force_resources: false
resource_stack:
 #Resource packs here are applied from bottom to top. This means that resources in higher packs will override those in lower packs.
 #Entries here must indicate the filename of the resource pack.
 #Example
 # - natural.zip
 # - vanilla.zip
 #If you want to force clients to use vanilla resources, you must place a vanilla resource pack in your resources folder and add it to the stack here.

```
